Repository zyu22/walk-or-run-client, pull requests merged in 2024-11, with the labels that each got.

#4 [markup] 로그인 화면 구현
  src/App.vue
  src/components/user/login.vue
  src/router/index.js
  src/views/UserView.vue
Labels: 🎨 Markup

#5 [markup] challenge 와이어프레임 생성
  src/components/dashboard/BarChart.vue
  src/components/dashboard/ChallengeDetailModal.vue
  src/components/dashboard/DateRangePicker.vue
  src/components/dashboard/DonutChart.vue
  src/components/dashboard/LineChart.vue
  src/components/dashboard/MetricCard.vue
  src/components/dashboard/Modal.vue
  src/components/dashboard/SideBar.vue
  src/router/index.js
  src/views/ChallengeView.vue
  src/views/FllowView.vue
  src/views/HomeView.vue
  src/views/UserView.vue
  src/views/challenge/ChallengeView.vue
  tailwind.config.js
Labels: 🎨 Markup

#8 [Markup] 사이드바 수정, 로그인 검사 기능 임시 삭제
  src/components/dashboard/SideBar.vue
  src/components/dashboard/Sidebar2.vue
  src/components/user/findEmail.vue
  src/components/user/findPassword.vue
  src/components/user/myGoal.vue
  src/components/user/myInfo.vue
  src/components/user/myPassword.vue
  src/components/user/register.vue
  src/router/index.js
  src/views/UserView.vue
Labels: 🎨 Markup

#11 [Markup] 마이페이지/ 내 비밀번호 관리, 마이페이지/ 내 목표 관리 마크업
  src/components/user/myGoal.vue
  src/components/user/myGoalForm.vue
  src/components/user/myInfo.vue
  src/components/user/myPassword.vue
  src/router/index.js
Labels: 🎨 Markup

#14 [Refactor] 비밀번호 확인용 질문 선택 방식 드랙드롭으로 변경
  src/components/user/myPassword.vue
Labels: 🛠️ Refactor

#16 [Markup] 이메일 찾기, 비밀번호 찾기, 회원가입하기 마크업 작성
  src/components/user/findEmail.vue
  src/components/user/findPassword.vue
  src/components/user/register.vue
  src/components/user/resetPassword.vue
  src/router/index.js
Labels: 🎨 Markup

#19 [Feat] 파일 업로드 기능 api 연결
  src/api/axios.js
  src/components/upload/upload.vue
  src/components/user/login.vue
  src/components/user/userGoal.vue
  src/components/user/userInfo.vue
  src/views/MyPageView.vue
  vite.config.js
Labels: 🚧 Feature

#24 [Refactor] 1. 사이드바 길이 조정 2. 운동시간, 이동거리 수식 변경
  src/App.vue
  src/components/user/dashboard/metricCard.vue
  src/components/user/dashboard/userDashboard.vue
Labels: 🛠️ Refactor

#45 [feat] 관리자 계정 로그인 시, 사용자 관리 기능
  .env
  src/api/axios.js
  src/components/admin/userInfo/settingUserInfo.vue
Labels: 🚧 Feature

#55 [refactor] 관리자 로그인 시 로그인페이지 다시 나오던 문제 해결
  src/App.vue
  src/components/admin/AdminSideBar.vue
  src/components/admin/challenge/addChallenge.vue
  src/components/admin/challenge/settingChallenge.vue
  src/components/admin/challenge/settingChallengeDetailModal.vue
  src/components/authentication/login.vue
  src/components/common/Calender.vue
  src/components/user/challenge/challenge.vue
  src/components/user/challenge/challengeDetailModal.vue
  src/router/index.js
  src/stores/user.js
Labels: ❌ Bug, 🛠️ Refactor
